const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];
const store = { get(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }, set(key, value) { localStorage.setItem(key, JSON.stringify(value)); } };

const modalBackdrop = $('#modalBackdrop'); const modalContent = $('#modalContent'); let timer = null; let secondsLeft = 0;
const questions = ['¿Qué necesitas darte permiso de sentir?', '¿Qué sería amable contigo en los próximos 10 minutos?', '¿Qué parte de tu día merece más espacio?', '¿Qué te gustaría recordar cuando termine este día?', '¿Qué sí está bajo tu control ahora?'];
const todayKey = () => new Date().toISOString().slice(0, 10);

function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); }
function markToday(label = 'Práctica completada') { const progress = store.get('weekProgress', {}); progress[todayKey()] = true; store.set('weekProgress', progress); renderWeek(); refreshProgress(); showToast(`${label}. Lo pequeño también cuenta.`); }
function closeModal() { clearInterval(timer); timer = null; modalBackdrop.hidden = true; document.body.style.overflow = ''; }

function setupTimer(type) {
  secondsLeft = type === 'breathing' ? 120 : 300; const display = $('#timerDisplay'); const label = $('#timerLabel'); const start = $('#timerStart');
  const update = () => { display.textContent = `${String(Math.floor(secondsLeft / 60)).padStart(2, '0')}:${String(secondsLeft % 60).padStart(2, '0')}`; };
  update(); start.addEventListener('click', () => { if (timer) return; start.textContent = 'En curso…'; label.textContent = type === 'breathing' ? 'Sigue el círculo · inhala y exhala' : 'Muévete con suavidad'; timer = setInterval(() => { secondsLeft--; update(); if (secondsLeft <= 0) { clearInterval(timer); timer = null; label.textContent = '¡Práctica completada!'; start.textContent = 'Completado ✓'; markToday(); } }, 1000); });
  $('#timerReset').addEventListener('click', () => { clearInterval(timer); timer = null; secondsLeft = type === 'breathing' ? 120 : 300; label.textContent = 'Listo para comenzar'; start.textContent = 'Comenzar'; update(); });
}
function openModal(type) {
  clearInterval(timer); timer = null;
  const views = {
    breathing: `<p class="eyebrow">Paso 1 · Mental · 2 min</p><h2 id="modalTitle">Respiración 4–6</h2><p class="modal-intro">Sigue el círculo: inhala cuando crece y exhala cuando vuelve a su tamaño. No tienes que forzar nada.</p><div class="timer-label" id="timerLabel">Listo para comenzar</div><div class="timer-display" id="timerDisplay">02:00</div><div class="modal-actions"><button class="button button-primary" id="timerStart">Comenzar</button><button class="button button-dark" id="timerReset">Reiniciar</button></div><p class="mini-note">Si contar te incomoda, respira naturalmente y enfócate solo en alargar suavemente la exhalación.</p>`,
    movement: `<p class="eyebrow">Paso 2 · Físico · 5 min</p><h2 id="modalTitle">Movimiento amable</h2><p class="modal-intro">Hazlo a tu ritmo. Completa cada bloque sin dolor: caminar en el lugar, círculos de hombros, estiramiento suave y respiración.</p><div class="timer-label" id="timerLabel">4 bloques · 1 min cada uno</div><div class="timer-display" id="timerDisplay">05:00</div><div class="modal-actions"><button class="button button-primary" id="timerStart">Comenzar</button><button class="button button-dark" id="timerReset">Reiniciar</button></div><p class="mini-note">Si algo duele o te marea, detente. Cuidarte no es exigirte.</p>`,
    social: `<p class="eyebrow">Paso 3 · Social · 3 min</p><h2 id="modalTitle">Mensaje de conexión</h2><p class="modal-intro">Elige a alguien. Puedes enviar este mensaje tal cual o adaptarlo a tu manera.</p><div class="mini-note" style="font-size:15px">“Hola, hoy pensé en ti. ¿Cómo estás realmente? No tienes que responder ahora, solo quería hacerte saber que me importas.”</div><button class="button button-primary" id="copyMessage" style="margin-top:18px">Copiar mensaje <span>↗</span></button><button class="button button-dark" id="doneSocial" style="margin:18px 0 0 8px">Ya lo envié ✓</button><p class="modal-intro" id="copyStatus"></p>`,
    values: `<p class="eyebrow">Paso 4 · Espiritual · 2 min</p><h2 id="modalTitle">Brújula de valores</h2><p class="modal-intro">Nombra lo que importa y conviértelo en una acción pequeña y posible.</p><label for="valueInput">Un valor importante para mí</label><input id="valueInput" placeholder="Ej. calma, honestidad, familia…" /><label for="actionInput">Hoy lo practicaré así</label><textarea id="actionInput" rows="3" placeholder="Una acción concreta y amable contigo…"></textarea><button class="button button-primary" id="saveValues">Guardar reflexión <span>→</span></button><p class="modal-intro" id="valueStatus"></p>`
  };
  modalContent.innerHTML = views[type]; modalBackdrop.hidden = false; document.body.style.overflow = 'hidden';
  if (type === 'breathing' || type === 'movement') setupTimer(type);
  if (type === 'social') { $('#copyMessage').addEventListener('click', async () => { const text = 'Hola, hoy pensé en ti. ¿Cómo estás realmente? No tienes que responder ahora, solo quería hacerte saber que me importas.'; try { await navigator.clipboard.writeText(text); $('#copyStatus').textContent = 'Mensaje copiado. Ahora envíalo cuando te sientas listo/a.'; } catch { $('#copyStatus').textContent = 'Selecciona y copia el mensaje desde el recuadro.'; } }); $('#doneSocial').addEventListener('click', () => { markToday('Conexión registrada'); closeModal(); }); }
  if (type === 'values') $('#saveValues').addEventListener('click', () => { const value = $('#valueInput').value.trim(); const action = $('#actionInput').value.trim(); if (!value || !action) { $('#valueStatus').textContent = 'Completa ambos campos para guardar tu reflexión.'; return; } store.set('lastReflection', { value, action, date: new Date().toLocaleDateString('es-MX') }); $('#valueStatus').textContent = 'Guardado en este dispositivo. Qué bonito elegir con intención.'; $('#saveValues').textContent = 'Guardado ✓'; markToday('Reflexión guardada'); });
}

$$('.open-exercise').forEach(button => button.addEventListener('click', () => openModal(button.dataset.modal)));
$('#modalClose').addEventListener('click', closeModal); modalBackdrop.addEventListener('click', e => { if (e.target === modalBackdrop) closeModal(); }); document.addEventListener('keydown', e => { if (e.key === 'Escape' && !modalBackdrop.hidden) closeModal(); });

$$('.mood-options button').forEach(button => button.addEventListener('click', () => { $$('.mood-options button').forEach(b => b.classList.remove('selected')); button.classList.add('selected'); store.set('moodToday', { mood: button.dataset.mood, date: new Date().toDateString() }); $('#moodMessage').textContent = 'Guardado. Gracias por escucharte hoy.'; showToast('Check-in guardado'); }));
const moodSaved = store.get('moodToday', null); if (moodSaved?.date === new Date().toDateString()) { $(`[data-mood="${moodSaved.mood}"]`)?.classList.add('selected'); $('#moodMessage').textContent = 'Ya registraste cómo te sientes hoy.'; }

function filterCards(filter = 'all', intent = '') { $$('.exercise-card').forEach(card => { const matchesCategory = filter === 'all' || card.dataset.category === filter; const matchesIntent = !intent || card.dataset.intents.includes(intent); card.classList.toggle('hidden-card', !(matchesCategory && matchesIntent)); }); }
$$('.category-tabs button').forEach(button => button.addEventListener('click', () => { $$('.category-tabs button').forEach(b => b.classList.remove('active')); button.classList.add('active'); $$('.intent-card').forEach(b => b.classList.remove('active')); filterCards(button.dataset.filter); }));
$$('.intent-card').forEach(button => button.addEventListener('click', () => { $$('.intent-card').forEach(b => b.classList.remove('active')); button.classList.add('active'); $$('.category-tabs button').forEach(b => b.classList.remove('active')); $('[data-filter="all"]').classList.add('active'); filterCards('all', button.dataset.filterIntent); document.querySelector('#biblioteca').scrollIntoView({ behavior: 'smooth', block: 'start' }); }));
$('#clearSearch').addEventListener('click', () => { $('#exerciseSearch').value = ''; $$('.intent-card').forEach(b => b.classList.remove('active')); $$('.category-tabs button').forEach(b => b.classList.remove('active')); $('[data-filter="all"]').classList.add('active'); filterCards(); });
$('#exerciseSearch').addEventListener('input', e => { const term = e.target.value.toLowerCase(); $$('.exercise-card').forEach(card => card.classList.toggle('hidden-card', !card.textContent.toLowerCase().includes(term))); });
$('#surpriseBtn').addEventListener('click', () => { const cards = $$('.exercise-card'); const card = cards[Math.floor(Math.random() * cards.length)]; openModal(card.querySelector('.open-exercise').dataset.modal); });

function refreshProgress() { const progress = store.get('weekProgress', {}); const now = Date.now(); const count = Object.keys(progress).filter(key => { const age = (now - new Date(`${key}T00:00:00`).getTime()) / 86400000; return age >= -1 && age < 7; }).length; $('#progressCount').textContent = count; $('#progressBar').style.width = `${Math.min(count / 7 * 100, 100)}%`; $('#progressMessage').textContent = count === 0 ? 'Empieza marcando una práctica.' : count === 1 ? 'Un día a la vez. Ya comenzaste.' : `${count} días de cuidado propio esta semana.`; }
function renderWeek() { const names = ['Lun','Mar','Mié','Jue','Vie','Sáb','Dom']; const today = new Date(); const monday = new Date(today); monday.setDate(today.getDate() - ((today.getDay() + 6) % 7)); const progress = store.get('weekProgress', {}); $('#weekDays').innerHTML = names.map((name, i) => { const date = new Date(monday); date.setDate(monday.getDate() + i); const key = date.toISOString().slice(0, 10); return `<div class="day"><span>${name}</span><button class="${progress[key] ? 'done' : ''}" data-day="${key}" aria-label="Marcar ${name}">${progress[key] ? '✓' : ''}</button></div>`; }).join(''); $$('.day button').forEach(button => button.addEventListener('click', () => { const p = store.get('weekProgress', {}); p[button.dataset.day] ? delete p[button.dataset.day] : p[button.dataset.day] = true; store.set('weekProgress', p); renderWeek(); refreshProgress(); })); }
renderWeek(); refreshProgress();

const savedJournal = store.get('journal', null); if (savedJournal) { $('#journalInput').value = savedJournal.text; $('#savedJournal').innerHTML = `<strong>Última nota · ${savedJournal.date}</strong><br>${savedJournal.text}`; }
$('#saveJournal').addEventListener('click', () => { const text = $('#journalInput').value.trim(); if (!text) { $('#journalStatus').textContent = 'Escribe algo antes de guardar.'; return; } const entry = { text, date: new Date().toLocaleDateString('es-MX') }; store.set('journal', entry); $('#savedJournal').innerHTML = `<strong>Última nota · ${entry.date}</strong><br>${entry.text}`; $('#journalStatus').textContent = 'Guardado localmente en este dispositivo.'; markToday('Nota guardada'); });
$('#refreshQuestion').addEventListener('click', () => { const current = $('#dailyQuestion').textContent; const available = questions.filter(q => q !== current); $('#dailyQuestion').textContent = available[Math.floor(Math.random() * available.length)]; });
$('#themeToggle').addEventListener('click', () => { document.body.classList.toggle('dark'); const dark = document.body.classList.contains('dark'); store.set('darkMode', dark); $('#themeToggle').textContent = dark ? '☾' : '☼'; }); if (store.get('darkMode', false)) { document.body.classList.add('dark'); $('#themeToggle').textContent = '☾'; }
$('#profileBtn').addEventListener('click', () => showToast('Tu espacio es privado: los datos viven en este navegador.'));
